خاصية رفع الكتاب
Fahad-Alsaidi/raqin pull request #11
Opened 2021-03-19 21:50 UTC by Sulaiman-SM

اضفت خاصية رفع الكتاب من الجهتين 
 api + ui
ولكن يحتاج للتحسين

2021-03-20 15:33 UTC, Fahad-Alsaidi requested changes
هناك ملاحظة بسيطة والأمور الأخرى طيبة

2021-03-20 15:33 UTC, Fahad-Alsaidi commented on raqin-ui/src/pages/project.vue
> +          accept=".csv,.txt,.xls,.xlsx,.doc,.docx,.pdf,.dbf,.zip,.rar,.7z,.jpg,.png,.gif"
في هذا المشروع نقبل فقط ملفات pdf 
المرحلة الأولى ولاحقا الملفات المضغوطو

2021-03-20 18:15 UTC, Sulaiman-SM commented on raqin-ui/src/pages/project.vue
> +          accept=".csv,.txt,.xls,.xlsx,.doc,.docx,.pdf,.dbf,.zip,.rar,.7z,.jpg,.png,.gif"
تم, سيتم التعديل إن شاء الله
وكذلك من ناحية api
سأضيف بعض التعديلات عليها

2021-03-22 19:02 UTC, Sulaiman-SM commented
@Fahad-Alsaidi 
انتهيت من التعديلات في الوقت الحالي

2021-03-22 19:03 UTC, Sulaiman-SM commented on raqin-ui/src/pages/project.vue
> +          accept=".csv,.txt,.xls,.xlsx,.doc,.docx,.pdf,.dbf,.zip,.rar,.7z,.jpg,.png,.gif"
انتهيت من التعديلات في الوقت الحالي
@Fahad-Alsaidi

2021-03-23 03:30 UTC, Fahad-Alsaidi approved these changes
شكرا جزيلا

2021-03-23 03:30 UTC, merged